Stopwords = {'an', "that'll", 'wouldn', 'doing', 'and', "it's", 'how', 'or', 'but',
             "aren't", 'having', 'with', 'be', 'between', 'under', 'was', 'had',
             'aren', 'where', 'yours', 'over', 't', 'this', 'because', 'again',
             'only', "you're", 'being', 'just', 'himself', "don't", 'than', "weren't",
             'themselves', 'what', 'yourselves', 'both', 'as', 'each', 'there', 'don',
             'couldn', 'up', "won't", 'have', 'ours', 'any', 'for', 'very', 'from', 'won',
             'those', 'here', 'by', 'your', 'didn', 'now', 'mightn', 'the', 'so', 'ma',
             'until', "haven't", 'i', 'most', 'hers', 'their', 'out', 'yourself', 'down',
             'nor', "isn't", "needn't", 'same', 'such', 'too', "hadn't", 'theirs', "shouldn't",
             'then', 'its', 'itself', 'did', 'into', 'own', 'am', 'my', 'which', 'some', 'against',
             'herself', 'when', 'that', 'her', "hasn't", 'we', 'few', 'is', 'y', 'who', "wasn't",
             'once', "mustn't", 'he', 'these', 'll', 'she', 'during', 'more', 'o', 'further',
             'other', 'if', 'doesn', 'myself', 'him', 'all', 'ourselves', 'about', 'been', 'at',
             'weren', 'do', "you've", 'they', 'no', 'should', "shan't", "you'll", "mightn't", 'are',
             'below', 'of', 'hadn', 'to', "you'd", 'before', 'you', 'shouldn', 'can', 'through', 'd',
             'mustn', 'it', 've', 'wasn', "doesn't", "couldn't", "she's", 'off', 'hasn', 'after', "should've",
             'while', 'shan', 's', 'on', 'were', "wouldn't", 'will', 'does', 're', 'our', 'has', 'in', 'them',
             'a', 'needn', 'whom', 'm', 'above', 'isn', 'why', 'not', 'his', 'ain', 'haven', 'me', "didn't",
             'tutorials', 'institute', 'classes', 'academy', 'centre', 'center', 'tutors', 'near', 'opposite',
             'behind', 'above'}
